import type { SubscriptionPlan } from '@/types';

export const plans: SubscriptionPlan[] = [
  {
    id: 'free',
    name: 'Free Tier',
    price: '₹0',
    currency: 'INR',
    duration: '/ forever',
    order: 0,
    features: [
      '🎯 Problem Generation & Insights:',
      '   • Guest: 10 interactions',
      '   • Logged: 20 interactions',
      '💬 Chat Interactions:',
      '   • Guest: Must login',
      '   • Logged: 15 per day',
      '📝 Test Creation:',
      '   • Guest: Must login',
      '   • Logged: 5 tests',
      '📊 Basic Analytics',
      '✨ Community Support'
    ],
    type: 'free',
    highlight: false,
  },
  {
    id: 'weekly',
    name: 'Weekly Pass',
    price: '₹249',
    currency: 'INR',
    duration: '/ week',
    order: 1,
    features: [
      '🎯 Unlimited Problem Generation & Insights',
      '💬 50 Chat Interactions per day',
      '📝 Create 10 Tests',
      '📊 Advanced Test Analysis',
      '🔗 Share Tests with Others',
      '📈 Personal Statistics Dashboard',
      '⚡ Fast Response Times',
      '🎨 Ad-Free Experience',
      '💡 Smart Suggestions'
    ],
    type: 'subscription',
  },
  {
    id: 'monthly',
    name: 'Monthly Saver',
    price: '₹699',
    currency: 'INR',
    duration: '/ month',
    order: 2,
    features: [
      '🎯 Unlimited Problem Generation & Insights',
      '💬 100 Chat Interactions per day',
      '📝 Create 20 Tests',
      '🔮 Genius Mode AI',
      '📊 Advanced Test Analysis',
      '🔗 Share Tests with Others',
      '📈 Detailed Performance Analytics',
      '⚡ Priority Support',
      '🎯 Personalized Study Plans',
      '📚 Premium Content Library'
    ],
    highlight: true,
    type: 'subscription',
  },
  {
    id: 'quarterly',
    name: 'Quarterly Pro',
    price: '₹1999',
    currency: 'INR',
    duration: '/ 3 months',
    order: 3,
    features: [
      '🎯 Unlimited Problem Generation & Insights',
      '💬 200 Chat Interactions per day',
      '📝 Create 30 Tests',
      '🔮 Genius Mode AI',
      '📊 Advanced Test Analysis & AI Insights',
      '🔗 Share Tests & Create Study Groups',
      '📈 Comprehensive Performance Analytics',
      '👥 Collaborative Study Features',
      '🏆 Progress Tracking & Achievements',
      '🚀 Early Access to New Features',
      '💎 Premium Support & Coaching'
    ],
    type: 'subscription',
  },
];
