
// src/app/terms-of-service/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
// Button removed as global header provides navigation
// import { Button } from '@/components/ui/button';
// ArrowLeft removed as global header provides navigation
// import { ArrowLeft } from 'lucide-react';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service - AOLBEAM',
  description: 'Terms of Service for AOLBEAM.',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      {/* Header is now global */}
      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 flex-grow">
        <div className="max-w-3xl mx-auto bg-card p-6 sm:p-8 rounded-lg shadow-lg">
          <h2 className="text-2xl font-semibold mb-6 text-center">Terms of Service</h2>
          
          <p className="mb-4 text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

          <div className="prose dark:prose-invert max-w-none">
            <p><strong>This is a placeholder Terms of Service. You should replace this content with your own comprehensive terms before going live. Consult with a legal professional.</strong></p>
            
            <h3 className="mt-6">1. Acceptance of Terms</h3>
            <p>By accessing or using AOLBEAM (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service.</p>

            <h3 className="mt-6">2. Use of Service</h3>
            <p>AOLBEAM provides AI-generated practice problems and related educational content. You agree to use the Service for lawful purposes only and in a manner that does not infringe the rights of, or restrict or inhibit the use and enjoyment of, this Service by any third party.</p>
            <p>Free usage is limited as described in the application. Subscriptions are required for unlimited access and additional features, subject to payment of applicable fees.</p>

            <h3 className="mt-6">3. User Accounts (If Implemented)</h3>
            <p>If user accounts are implemented, you will be responsible for safeguarding your account information and for all activities that occur under your account.</p>
            
            <h3 className="mt-6">4. Intellectual Property</h3>
            <p>The Service and its original content (excluding content provided by users or generated for users by AI), features, and functionality are and will remain the exclusive property of AOLBEAM and its licensors. The content generated by AI for your use is for your personal, non-commercial educational purposes, subject to these Terms.</p>

            <h3 className="mt-6">5. Subscriptions and Payments (If Implemented)</h3>
            <p>Details regarding subscription plans, fees, payment terms, and cancellation policies will be provided at the point of subscription. All payments are non-refundable except as required by law or as explicitly stated.</p>

            <h3 className="mt-6">6. Disclaimer of Warranties</h3>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. While we strive to provide accurate and helpful content, we make no warranties, express or implied, regarding the accuracy, reliability, or completeness of any information or content provided through the Service. AI-generated content may contain inaccuracies or errors.</p>

            <h3 className="mt-6">7. Limitation of Liability</h3>
            <p>In no event shall AOLBEAM, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

            <h3 className="mt-6">8. Governing Law</h3>
            <p>These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.</p>

            <h3 className="mt-6">9. Changes to Terms</h3>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page.</p>

            <h3 className="mt-6">10. Contact Us</h3>
            <p>If you have any questions about these Terms, please <Link href="/contact-us" className="text-primary hover:underline">contact us</Link>.</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

    